### PR TITLE
Build and deploy docker image on master commit or tag

### LINKED ISSUE #15: Add a tag to dockerhub image
To pull an image from [dockerhub](https://hub.docker.com/r/krateng/maloja/tags) a tag is required. Please tag the image build with `latest`! Thanks

### PR DESCRIPTION
**Pull request by FoxxMD**
Automate docker image deployment to dockerhub using repository triggers

* Deploys an image to `latest` tag on dockerhub when commits are pushed to the `master` branch
* Deploys an image to version tag `X.XX.XX` on dockerhub when a new tag on github is made

Closes #15

### CODE REVIEW

**Comment by krateng** [comment]
Looks like that worked, thank you! Please let me know if the image works correctly, then I'll update the Readme link.

**Comment by FoxxMD** [comment]
Deployed and everything works as expected 👍 My server running at https://scrobble.mattfoxx.me is running on [krateng/maloja:latest](https://hub.docker.com/layers/krateng/maloja/latest/images/sha256-b59fa070cd03004d56a10ddb969e2efca893757ae4b2eb61a96f48547b1f6b2e?context=explore)

**Comment by mannp** [comment]
> Please let me know if the image works correctly, then I'll update the Readme link.

Image works for me, many thanks for creating :)

**Comment by FoxxMD** [comment]
@krateng  Can also add a docker pull badge with this code:

```
[![](https://img.shields.io/docker/pulls/krateng/maloja?style=for-the-badge)](https://hub.docker.com/r/krateng/maloja/tags)
```

**Comment by Joniator** [comment]
v2.12.18 seems to build fine, I guess it was just delayed because I do not actively monitor with hooks for new releases, but check daily at 1am for something new to build.
Glad to have this properly baked in your release process. I updated the description of my image and the repo to point to your images.

**Comment by krateng** [comment]
@Joniator Thank you for maintaining your build all this time, I really appreciate it!

If I read it correctly, the current build will just create a new Docker image with the current version that downloads the latest version from PyPI all the same. Your build specifically downloads the correct version for each build (`pip install malojaserver=$MALOJA_RELEASE`). Am I assuming this variable could also be set in the Github Action somehow so this behaviour is preserved?

**Comment by FoxxMD** [comment]
@krateng that is correct the image that is built will always be based on the latest version found from pip. So really the docker image depends on pip already having the latest image...

I will re-write the dockerfile to build from source which should be the actual behavior. IE when it builds `latest` from `master` it should be checking out the `master` branch and building from there. Same for tags (building from commit at tag).

I will use my comment [here](https://github.com/krateng/maloja/issues/57#issuecomment-754269302) as a base but any advice/hints you can give on what would be necessary to build from source on a **clean install** (such as library dependencies outside of pip) would be helpful

**Comment by FoxxMD** [comment]
I understand your position but I think you are missing one of the key features of a project dockerfile: it should be able to build the code that the repository contains at any arbitrary commit (using the dockerfile available at that commit). This is useful not just for end users but also any future contributors.

If I'm a developer who wants to contribute to Maloja I may wish to make some code changes and then **test that those changes will work for all users** by building them, with the dockerfile, into the "clean build". If they work there I can be reasonably sure they will work everywhere.

>  there is probably no reason to ever need an older version

If there _was_ a need to for an older version, specifically at a certain commit, it would be beneficial to be able to build the project from that point.

**Concerning inconsistencies**

The dockerfile I've got working is pretty simple and actually just [uses pip to do a local install](https://pip.pypa.io/en/stable/cli/pip_install/#local-project-installs) of the repository like this:

```
...
RUN apk add --no-cache --virtual .build-deps \
    gcc \
    libxml2-dev \
    libxslt-dev \
    libc-dev \
    py3-pip \
    linux-headers \
    && \
    pip3 install psutil

# First copy maloja requirements and install dependencies
COPY requirements.txt ./

RUN pip3 install --no-cache-dir -r requirements.txt

# Copy the rest of the project into dir
COPY . .

# Then install local project using pip
RUN pip3 install /usr/src/app
...
```

The container eventually just executes `maloja run` so its as close to using the pypi version as possible, but straight from source.

> a quick way to simply check the current PyPI version (or use the git tag), only build if that version doesn't exist yet, and then have the image refer to that specific version

I think I can swing this as well. Using @Joniator repo as a template I can set up a scheduled job with github actions to do what his is doing. 

I would strongly advise for publishing different tags based on the source of each image, though. It's your call on which of these you'd like publish:

* `latest` => Build from repository
* `pypi-latest` => Build from latest pypi version
* `X.XX.XX` => build from github tag
* `pypi-X.XX.XX` => build from pypi versions

**Comment by krateng** [comment]
Fair enough, let's go with the direct build from source then. I'll try to be disciplined with proper commit tagging :D

**Pull request merged**
