### PR TITLE
make `auth.getMobileSession` return XML

### PR DESCRIPTION
**Pull request by duckfromdiscord**
#292

XML will now return from `auth.getMobileSession`, but not scrobbling yet.

### CODE REVIEW

**Comment by duckfromdiscord** [comment]
The Last.FM API actually has options to return both JSON and XML, but I believe XML is supposed to be returned by default. Feel free to either close or merge this PR.

**Comment by krateng** [comment]
Do you have a scrobbler that fails because of this? I'm a bit anxious about changing behaviour that someone's workflow might rely on.

**Comment by duckfromdiscord** [comment]
> Do you have a scrobbler that fails because of this? I'm a bit anxious about changing behaviour that someone's workflow might rely on.

@krateng Yes actually, this came up because I was helping reconfigure the game Audiosurf 2 (not Audiosurf 1 which [I already implemented maloja scrobbling for](https://github.com/duckfromdiscord/as-scrobbler/)) and since the way to do that is to redirect Last.FM Audioscrobbler 2.0 queries to maloja, it actually fails when JSON is returned as I found out by checking it with Fiddler.

**Comment by krateng** [comment]
Alright, could you add a little check so that we still return the old json when the argument asks for it?

**Comment by duckfromdiscord** [comment]
This last commit should do that. I'm not sure of any projects that require json to test with, but I do know Audiosurf 2 works with this.

**Comment by duckfromdiscord** [comment]
Does nimrodel support setting the MIME type for XML?

**Comment by duckfromdiscord** [comment]
Is there anything else needed to get this PR merged? I'm using the XML feature a lot and I've been stuck on my own fork for the feature. Shall I also convert `submit_scrobble` for consistency or would you rather I stick to only changing `authmobile` to change less stuff?

**Pull request merged**
