### PR TITLE
Quick fork

### PR DESCRIPTION
**Pull request by bearlikelion**
This project looks interesting!
Hoping to directly scrobble from Spotify if possible.

Made some small tweaks so the program can run in Windows and to throw an error when no arguments passed.

I changed /usr/env/python3 to python, might need to fix this or alias it (no python3 for me in Windows)

### CODE REVIEW

**Comment by bearlikelion** [comment]
There are issues with SetProcTitle on Windows, and I accidentally added to much to requirements based on my previous vENV

**Comment by bearlikelion** [comment]
Resolved issue with SetProcTitle on Windows
Allow empty settings to be entered (was causing crash)
Updated README.md with changes
Fallback for python executable if python3 doesn't exist

**Comment by justinas** [comment]
:clap: on adding requirements.txt, I was just about to create an issue for that. The whole `install` "subcommand calling pip" thing feels icky :confused:

**Comment by krateng** [comment]
Thanks for the contribution!

Linux always has first priority of course, so I'd like to keep Windows-compatibility as non-invasive as possible. Could you elaborate on the Python 3 issue? Does Windows not have Python 3 or can it simply not be called with the python3 command? Is there any way to alias that?

What is the crash caused by empty settings? The None setting is necessary to declare that the user has explicitly specified to not use an API key.

**Comment by krateng** [comment]
Empty settings issue should be fixed with a doreah update, see krateng/doreah#d7600228df85a64421865774bdbf95ba1ddcd46e

**Comment by krateng** [comment]
Empty settings issue should be fixed with a doreah update, see d7600228df85a64421865774bdbf95ba1ddcd46e

**Comment by krateng** [comment]
Closing this for now as some of the changes have been implemented. If you're still interested in Windows compatibility, you are of course welcome to reopen or open a new PR.

**Pull request closed without merging**
