### PR TITLE
Version 3

### PR DESCRIPTION
**Pull request by krateng**
Version 3 is now in Beta.

### What it does

Version 3 upgrades to a proper SQLite database. This gets rid of the long startup times of the server (except the very first time when your data has to be migrated). On its own it doesn't do much else for you, but it's the groundwork for many future improvements.

### Running it

I always welcome beta testers, so if you'd like to switch early, thank you! Your data should be perfectly safe, but you can always backup your data folder to make sure (which you should do regularly anyway for all your self-hosted software!)

If you're new here and would like to try out Maloja, you should consider starting with this beta right away to avoid having to go through the data migration later.

This is how you run v3:

* Clone this repository and checkout branch v3:
   ```
  git clone https://github.com/krateng/maloja
  cd maloja
  git checkout v3
   ```
* For a system installation, install dependencies with e.g.
   ```
   sh ./install/install_dependencies_alpine.sh
   ```
   then install the package with
   ```
   pip install .
   ```
   and run with
   ```
   maloja start
   ```
* For a podman / docker installation, build with
   ```
   podman build -t maloja . -f Containerfile
   ```
   then run with
   ```
   podman run --rm -p 42010:42010 -v $HOME/malojadata:/mlj -e MALOJA_DATA_DIRECTORY=/mlj maloja
   ```
   or an equivalent command / compose-file according to your own setup.
   (replace `podman` with `docker` if applicable).

### Having problems?

If you encounter any issues, please [report](https://github.com/krateng/maloja/issues/new?title=%5Bv3%5D%20) them. If you're not sure about something or have questions, feel free to ask below in this thread!

### CODE REVIEW

**Comment by FoxxMD** [comment]
Congrats on a major milestone! I'm still in initial startup but a few things I found:

# .dockerignore

Need to remove slashes from names like this:

```
*
!maloja
!Containerfile
!requirements_pre.txt
!requirements.txt
!pyproject.toml
!README.md
!LICENSE
```

When slashes were included it wouldn't build because `/requirements_pre.txt` only matches folders (I'm pretty sure) so it wasn't added to the build context. Docker will automatically match against any **file or folder** at root level with the patterns above so you don't need to worry about whether is a file or folder.

# No log output?

I see the container doing work BUT there is no log output -- at least [using portainer with default settings.](https://user-images.githubusercontent.com/4663766/162508141-05ee7d2c-59c2-4fa6-ace3-7c772df3aed9.png) . I can access the ui with the "performing upgrade" message and my data folder is refreshing the sqlite journal so its definitely working, just not seeing output from the docker logs for some reason.

**Comment by krateng** [comment]
Thanks! Looks like I never switched the upgrade from normal console output to proper file logging, I'll fix it!

**Comment by FoxxMD** [comment]
I believe all you need to do is stream logs to stderr and stdout, docker should take care of the rest.

Love the new settings page btw.

One last thing that isn't a dealbreaker because its always been this way but I'm now more aware of it (due to issues in my own projects haha) is **docker file permissions for mounted directories.** Docker (and the alpine base) run CMD/ENTRYPOINT as the default user which is always `root`. 

This means when maloja creates (and modifies??) files/folders they are owned by `root` (`0:0` for `uid:gid`). For windows/macos **hosts** this isn't a problem because docker already runs in a VM that takes care of this but for **linux hosts** this [becomes an issue](https://user-images.githubusercontent.com/4663766/162510187-f49388b3-7b69-4a73-a4d6-b3789ff9ed31.png) if you (the host) want to do anything with those files/folders besides reading them.

There's also no silver bullet for this problem. 

Docker provides [`--user`](https://docs.docker.com/engine/reference/run/#user) to allow specifying the `uid:gid` of the user who executes cmd/entrypoint which fixes permissions but can cause havok if your container is expected `root` or some other user to be running commands.

I'm personally using [PUID and PGID with a linuxserver base](https://docs.linuxserver.io/general/understanding-puid-and-pgid) which a better solution but still requires a user to know and add the correct ids as environmental variables to to the docker run command.

Anyway...its not something you need to fix right now since the original docker container does the same thing but definitely something to keep in mind IE can maloja run as non-root? can you implement (Add a user) to the alpine container to run as non-root? Which permission approach would you prefer?

**Comment by krateng** [comment]
The problem is that when running the container rootless with podman, the host user becomes the container root, so when the process runs as another user inside the container, that user is mapped to a third user on the host - which gives the mounted directories weird ownerships (uid and gid without name).

I'm not sure how to fix this so both docker and podman work equally well, but I'll definitely have another look at that.

**Comment by mannp** [comment]
Cool, congrats on the upcoming v3 👍🏻 

Wondered if there was a pre-release docker build available to test at all :)

**Comment by krateng** [comment]
Thanks!

I'm not pushing a build to dockerhub as it would automatically pull for everyone who has setup their system to pull without a tag, but you can build from source. But full release is probably gonna be very soon anyway :)

**Pull request merged**
