### PR TITLE
Add reparse scrobble feature

### PR DESCRIPTION
**Pull request by alim4r**
This PR adds a reparse feature and is similar to the delete scrobble feature.
In admin mode a refresh symbol is displayed next to the delete/trash symbol to reparse a scrobble from the `rawscrobble`.

Right now this is only a draft and works partially. The `Confirm` button can be pressed and the scrobble gets reparsed (refresh page).

#### `maloja/apis/native_v1.py`
- `reparse_scrobble` POST endpoint

#### `maloja/database/__init__.py`
- `def rawscrobble_to_scrobbledict` to transform a rawscrobble to scrobbledict (refactored from incoming_scrobble)
- `def incoming_scrobble` use `rawscrobble_to_scrobbledict`
- `def reparse_scrobble(timestamp)` updates scrobble `track_id` if `rawscrobble` generates a new `track_id`

#### `maloja/database/sqldb.py`
- `def update_scrobble_track_id` updates the track_id of a given scrobble timestamp
- `def get_scrobble` to get a scrobble

### TODO
- [x] Fix jinja template (icon placement & confirmation dialog)
- [ ] Add refresh icon
- [ ] Maybe also refresh the current scrobble after reparsing (Page has to be refreshed to see changes at the moment)

### CODE REVIEW

**Comment by krateng** [comment]
Nice work! I'll have a more in-depth look at it later.

**Comment by alim4r** [comment]
> Nice work! I'll have a more in-depth look at it later.

Thanks! I don't know much about jinja/css so i probably gonna revert those ui changes.. Just a quick addition to test the functionality.

Demo changing an artist with `replaceartist`:

maloja

**Comment by krateng** [comment]
Hey, would you mind merging `feature-webedit` into this branch and changing the PR target to it as well? Should only have one merge conflict, just readd your new function in `native_v1.py` below the edited ones. I can do it too if you want, just don't wanna push anything while you're potentially working on it.

**Comment by alim4r** [comment]
Yes, I can do that. Do you want me to keep the CSS changes in?

**Comment by krateng** [comment]
Yeah, they shouldn't conflict with anything.

**Comment by alim4r** [comment]
Does your branch work? Not sure if I messed something up with the merge?
I get this error after merging

```python
Traceback (most recent call last):
  File "C:\development\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\development\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\git\maloja\maloja\__main__.py", line 132, in <module>
    def main(*args,**kwargs):
  File "C:\development\Python\Python39\lib\site-packages\doreah\control.py", line 57, in decorator
    wrapper()
  File "C:\development\Python\Python39\lib\site-packages\doreah\control.py", line 51, in wrapper
    result = func(*args,**kwargs)
  File "C:\git\maloja\maloja\__main__.py", line 163, in main
    return action(*args,**kwargs)
  File "C:\git\maloja\maloja\__main__.py", line 95, in run_server
    from . import server
  File "C:\git\maloja\maloja\server.py", line 142, in <module>
    init_apis(webserver)
  File "C:\git\maloja\maloja\apis\__init__.py", line 12, in init_apis
    from . import native_v1
  File "C:\git\maloja\maloja\apis\native_v1.py", line 50, in <module>
    database.exceptions.EntityExists: lambda e: (409,{
AttributeError: module 'maloja.database' has no attribute 'exceptions'
```

**Comment by krateng** [comment]
That is odd. Do you have the file `exceptions.py` in `maloja/database`?

**Comment by alim4r** [comment]
Ah sorry had a old version of your branch locally

**Comment by alim4r** [comment]
Merged it and changed the target branch

**Comment by krateng** [comment]
Thanks for the contribution! Merged into the feature branch, will be in the release hopefully in a few days at most!

**Pull request merged**
