### PR TITLE
README.md: docker import suggestion

### LINKED ISSUE #126: Error when browsing past years
I have successfully imported my last.fm. Thanks for the time fix.

When I open scrobbles page for year (/scrobbles?in=2013) it fails for some of them. I can open most of years but 2 of them produce 500 server error.

Logs produced
```
[thirdparty] Got track image for (['The Agonist'], 'Remnants in Time') from Deezer
[thirdparty] Could not get track image for (['Deathbeds AU'], 'A Night in Hell') from Deezer
[server] Waitress Task Queue Depth at 13
Traceback (most recent call last):
  File "/usr/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib/python3.9/site-packages/maloja/server.py", line 275, in jinja_page_public
    return jinja_page(name)
  File "/usr/lib/python3.9/site-packages/maloja/proccontrol/profiler.py", line 28, in newfunc
    result = func(*args,**kwargs)
  File "/usr/lib/python3.9/site-packages/maloja/server.py", line 260, in jinja_page
    res = template.render(**loc_context)
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/lib/python3.9/site-packages/maloja/web/jinja/scrobbles.jinja", line 7, in top-level template code
    {% set scrobbles = dbc.get_scrobbles(filterkeys,limitkeys,amountkeys) %}
  File "/usr/lib/python3.9/site-packages/maloja/database/jinjaview.py", line 42, in packedmethod
    result = originalmethod(**kwargs,dbconn=self.conn)
  File "/usr/lib/python3.9/site-packages/maloja/database/__init__.py", line 62, in newfunc
    return func(*args,**kwargs)
  File "/usr/lib/python3.9/site-packages/maloja/database/__init__.py", line 164, in get_scrobbles
    result = sqldb.get_scrobbles(since=since,to=to,dbconn=dbconn)
  File "/usr/lib/python3.9/site-packages/maloja/database/dbcache.py", line 56, in outer_func
    result = inner_func(*args,**kwargs,dbconn=conn)
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 114, in wrapper
    return func(*args,**kwargs)
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 420, in get_scrobbles
    result = scrobbles_db_to_dict(result)
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 161, in scrobbles_db_to_dict
    tracks = get_tracks_map(set(row.track_id for row in rows))
  File "/usr/lib/python3.9/site-packages/maloja/database/dbcache.py", line 88, in outer_func
    remaining = inner_func(set(e for e in set_arg if e not in result),dbconn=conn)
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 118, in wrapper
    return func(*args,**kwargs)
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 604, in get_tracks_map
    trackdicts = tracks_db_to_dict(result)
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 184, in tracks_db_to_dict
    return [
  File "/usr/lib/python3.9/site-packages/maloja/database/sqldb.py", line 186, in <listcomp>
    "artists":artists[row.id],
KeyError: 22761

```

### LINKED ISSUE #127: All time scrobbles count is always 0
After spotify + last.fm import + restarting container to clear the cache. Any ideas?

Screenshot from 2022-04-21 22-35-57

### PR DESCRIPTION
**Pull request by northys**

### CODE REVIEW

**Comment by krateng** [comment]
So this fully fixed both issues?

**Comment by northys** [comment]
Yeah, I dropped data, imported before starting maloja web server and now I can browse all years without 500. Also All Time now shows correct count.

Screenshot from 2022-04-23 16-14-14

**Comment by northys** [comment]
So it fixes also #125. I'll reword the commit.

**Comment by krateng** [comment]
Great! I did change the code a bit so that importing while running the server should now be somewhat safer, but still probably a good idea to advise against it.

**Pull request merged**
